# Generated by Django 4.2.1 on 2023-05-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_favorite_base_spirits_and_more'),
    ]
    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fav_base_spirits',
            new_name='favorite_base_spirits',
        ),
    ]

