# Generated by Django 4.2.1 on 2023-05-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_column',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
