# Generated by Django 4.2.1 on 2023-05-18 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_new_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favorite_base_spirits',
            new_name='fav_base_spirits',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='new_column',
        ),
    ]
