# Generated by Django 4.2.1 on 2023-05-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_favorite_base_spirits_profile_fav_base_spirits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fav_base_spirits',
            new_name='favorite_base_spirits',
        ),
    ]
