# Generated by Django 4.2.1 on 2023-05-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://images.pexels.com/photos/4439444/pexels-photo-4439444.jpeg', max_length=500),
        ),
    ]
