# Generated by Django 4.2.1 on 2023-05-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://i.pinimg.com/originals/6c/5e/d8/6c5ed86973bd0d669cae0a53568bdc70.jpg', max_length=500),
        ),
    ]
