# Generated by Django 4.2.1 on 2023-05-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_ingredients',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='/mixing.png', max_length=500),
        ),
    ]
