# Generated by Django 4.2.1 on 2023-05-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_item_item_ingredients_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_ingredients',
            field=models.CharField(max_length=500),
        ),
    ]
